In [6]:
import cv2
import numpy as np
import glob

#path = r'./images_before_removal/*.jpg'
#imagePaths = glob.glob(path)

for path in imagePaths:
    # Load the image
    image = cv2.imread(path)
    image_name = path.split('/')[-1]

    # Create a CascadeClassifier object for license plate detection
    plate_cascade = cv2.CascadeClassifier('haarcascade_russian_plate_number.xml')

    # Convert the image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Detect license plates in the image
    plates = plate_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)
    if len(plates) > 0:
        mod_plates = []
        for plate in plates:
            (x, y, w, h) = plate
            print(plate)
            imageheight, _, _ = image.shape
            if (y > 100 and (x <=410 or x >= 610)):
                mod_plates.append(plate)

        # Optional: Draw rectangles around the detected license plates
        # for (x, y, w, h) in plates:
        #     cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 10)

        # Apply Gaussian blurring to the detected license plates
        for (x, y, w, h) in mod_plates:
            roi = image[y:y+h, x:x+w]
            blurred_roi = cv2.GaussianBlur(roi, (255, 255), 0)
            image[y:y+h, x:x+w] = blurred_roi

        # Optional: Display the image with the detected license plates
        # cv2.imshow('Image', image)
        # cv2.waitKey(0)
        # cv2.destroyAllWindows()

    # Save the anonymized image to disk
    cv2.imwrite('./images_after_removal/' + image_name, image)

[898 404  77  25]
[545  25 136  45]
[846 169 115  38]
[865 289  88  29]
[820 232  88  29]
[908 196 125  42]
[923 171 133  44]
[515  29 144  48]
[321 117 140  47]
[824 164 110  37]
[873 172 120  40]
[836 155 104  35]
[875 171 122  41]
[498  32 149  50]
[926 176 140  46]
[847 169 107  36]
[817 222 100  33]
[519  28 140  47]
[928 169 137  46]
[876 176 113  38]
[503  42 143  48]
[891 319  84  28]
[275 130 140  47]
[927 201 118  39]
[ 32 183 143  48]
[943 167 130  43]
[525  21 141  47]
[893 186 122  41]
[526  20 144  48]
[820 227  92  31]
[938 193 129  43]
[873 301  96  32]
[863 374  82  27]
[824 228  94  31]
[872 172 124  41]
[856 366  78  26]
[287 127 145  48]
[843 155 104  34]
[828 165  96  32]
[832 259  92  31]
[523  23 140  47]
[935 167 135  45]
[178 136 174  58]
[868 173 114  38]
[500  42 140  47]
[540  23 148  49]
[929 174 130  43]
[524  33 137  46]
[877 177 107  36]
[501  44 144  48]
[537  44 120  40]
[932 184 130  43]
[931 201 129  43]
[535  28 142  47]
[263 133 146  49]
[167 141 1