In [17]:
import cv2
import numpy as np
import glob

path = r'./images_before_removal_custom_handling/*.jpg'
imagePaths = glob.glob(path)

for path in imagePaths:
    # Load the image
    image = cv2.imread(path)
    image_name = path.split('/')[-1]

    # Create a CascadeClassifier object for license plate detection
    plate_cascade = cv2.CascadeClassifier('haarcascade_russian_plate_number.xml')

    # Convert the image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Detect license plates in the image
    plates = plate_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)
    if len(plates) > 0:
        mod_plates = []
        for plate in plates:
            (x, y, w, h) in plate
            print(plate)
            imageheight, _, _ = image.shape
            if (y > 120):
                mod_plates.append(plate)

        # Optional: Draw rectangles around the detected license plates
        # for (x, y, w, h) in plates:
        #     cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 10)

        # Apply Gaussian blurring to the detected license plates
        for (x, y, w, h) in mod_plates:
            roi = image[y:y+h, x:x+w]
            blurred_roi = cv2.GaussianBlur(roi, (255, 255), 0)
            image[y:y+h, x:x+w] = blurred_roi

        # Optional: Display the image with the detected license plates
        # cv2.imshow('Image', image)
        # cv2.waitKey(0)
        # cv2.destroyAllWindows()

        # Save the anonymized image to disk
        cv2.imwrite('./images_after_removal/' + image_name, image)

[545  25 136  45]
[519  28 140  47]
[928 169 137  46]
[935 167 135  45]
[523  23 140  47]
[540  23 148  49]
[539  23 139  46]
[516  25 149  50]
[933 170 135  45]
[543  25 144  48]
[931 169 135  45]
[530  22 138  46]
[539  22 131  44]
[539  21 138  46]
[548  28 138  46]
[543  25 132  44]
[544  26 136  45]
[557  30 121  40]
